# Generated by Django 4.1.4 on 2023-07-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='User',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
